from shop.ShopRouter import ShopRouter

# LOGIN PAGE

R_XPATH_LOGIN_PAGE_AUTH_ERROR = '//div[@class = "alert alert-danger"]'
R_XPATH_LOGIN_PAGE_AUTH_SUCCESS = '//div[@class = "alert alert-success"]'
R_XPATH_LOGIN_PAGE_FORM_GROUP_FOR_INPUT_FIELD = '//div[contains(@class, "form-group has-feedback")]'
R_XPATH_LOGIN_PAGE_LOGIN_INPUT_FIELD = '//input[@name = "login"]'
R_XPATH_LOGIN_PAGE_PASSWORD_INPUT_FIELD = '//input[@name = "password"]'
R_XPATH_LOGIN_PAGE_REGISTER_MAIN = '//div[@class = "register-main"]'
R_XPATH_LOGIN_PAGE_SUBMIT_BUTTON = '//button[@type = "submit"][contains(@class, "btn btn-default")]'

XPATH_LOGIN_PAGE_FORM_GROUP_FOR_INPUT_FIELD =\
	R_XPATH_LOGIN_PAGE_REGISTER_MAIN + R_XPATH_LOGIN_PAGE_FORM_GROUP_FOR_INPUT_FIELD
XPATH_LOGIN_PAGE_LOGIN_INPUT_FIELD =\
	R_XPATH_LOGIN_PAGE_REGISTER_MAIN + R_XPATH_LOGIN_PAGE_LOGIN_INPUT_FIELD
XPATH_LOGIN_PAGE_PASSWORD_INPUT_FIELD =\
	R_XPATH_LOGIN_PAGE_REGISTER_MAIN + R_XPATH_LOGIN_PAGE_PASSWORD_INPUT_FIELD
XPATH_LOGIN_PAGE_SUBMIT_BUTTON =\
	R_XPATH_LOGIN_PAGE_REGISTER_MAIN + R_XPATH_LOGIN_PAGE_SUBMIT_BUTTON

# HOME PAGE

R_XPATH_AUTH_BTN_GROUP = '//div[@class = "btn-group"]'
R_XPATH_AUTH_LOGIN_IN_ACCOUNT_DROPDOWN_MENU = f'//a[@href = "{ShopRouter.ROUTE_LOGIN}"]'

XPATH_AUTH_ACCOUNT_BUTTON = R_XPATH_AUTH_BTN_GROUP + '/a[@class = "dropdown-toggle"]'
XPATH_AUTH_ACCOUNT_DROPDOWN_MENU = R_XPATH_AUTH_BTN_GROUP + '/ul[@class = "dropdown-menu"]'
XPATH_AUTH_LOGIN_IN_ACCOUNT_DROPDOWN_MENU =\
	XPATH_AUTH_ACCOUNT_DROPDOWN_MENU + R_XPATH_AUTH_LOGIN_IN_ACCOUNT_DROPDOWN_MENU
